name: Validate & Deploy site

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Validate HTML
      uses: snikch/html-validator-action@v1.0.0
      with:
        directory: .
        ignoreWarnings: true   # You can set this to false if you want strict validation

    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: .

    - name: Deploy to GitHub Pages
      id: deploy
      uses: actions/deploy-pages@v4
