name: Validate & Deploy site

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Validate HTML
      uses: abeltonder/html-validate-action@v1

    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: .

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
